### ISSUE TITLE
High contrast of the image background in the intro section

### ISSUE THREAD

**Issue by IrfanSalim** [Prashant0664/Blog-website#12]
In the intro image, the contrast is high and hurts the eyes, and also due to the similar color of the text, it's hard to read.

Suggestion: Use the image as a background image for the div and add a bit of color gradient so it mixes well with the website theme and is easy to read.

Current ~
![image](https://github.com/Prashant0664/Blog-website/assets/109443065/ee31e71e-561d-480e-9a55-f387597aa1e0)

Suggested ~
![image](https://github.com/Prashant0664/Blog-website/assets/109443065/c1c6be5e-76af-4cfd-bc46-1d492ee9768d)

**Comment by Prashant0664** [comment]
Thanks for your suggestion😀

**Comment by IrfanSalim** [comment]
If you are aligned, I would like to work on this.

Let me know what you think about it.

**Comment by Prashant0664** [comment]
@IrfanSalim instead of decreasing too much of contrast, try adding a layer of lightly transparent black screen in front of image, and back of text so that text will be easily visible and background brightness will decrease. Can cou work on this?
