### ISSUE TITLE
[Feature] Add dockerfile for the blog-website

### ISSUE THREAD

**Issue by deepak4566** [Prashant0664/Blog-website#17]
Add dockerfile for the blog-website with all dependencies and to run  quickly lauch application quickly

**Comment by deepak4566** [comment]
@Prashant0664 //

**Comment by Prashant0664** [comment]
I’m not very familiar with Docker at the moment, but I plan to learn it in the near future and look forward to integrating it into my projects. Thank you for the suggestion😊!

**Comment by deepak4566** [comment]
Hey, @Prashant0664 I can help in writing dockerfile but before that I need to know how did u deploy the dynamic working application in vercel,I want to know all commands  and dependencies that u have used to write dockerfile.

**Comment by deepak4566** [comment]
Because dockerfile need to consists all of those as its container

**Comment by deepak4566** [comment]
@Prashant0664 Actually prashath I'm sr.devops enginner and founder, so I'm also part of ngo called as service for mankind ,we wanted to develop a blog website  for that,I found ur repo,may if u can setup the same for our organization it could very much  here https://stmorg.in/

**Comment by deepak4566** [comment]
We always give  developer credits,we value your work

**Comment by Prashant0664** [comment]
> Hey, @Prashant0664 I can help in writing dockerfile but before that I need to know how did u deploy the dynamic working application in vercel,I want to know all commands and dependencies that u have used to write dockerfile.

```
Vercel is a serverless platform with support for 35+ frontend frameworks and does not support running docker instances.
While you can't deploy Docker images to Vercel directly, you can use Docker as part of your local development workflow when building for Vercel.
```

I did not use Dockerfile in my project. 
To deploy other projects on vercel:

- Link Github with Vercel
- Give Repo permission by going to Github->Settings->Integrations->Vercel
- Select Add New->Project 
- Filled required fields asked including tech stack etc.
- It will automatically deploy the project accordingly.
- You can use many other features like analytics, organization etc. in vercel.
https://vercel.com/
https://vercel.com/docs/cli

**Comment by Prashant0664** [comment]
> @Prashant0664 Actually prashath I'm sr.devops enginner and founder, so I'm also part of ngo called as service for mankind ,we wanted to develop a blog website for that,I found ur repo,may if u can setup the same for our organization it could very much here https://stmorg.in/

Nice to know! 
Apologies, sir, but due to my current academic commitments and a lot of academic workload, I won't be able to contribute directly to your project😔.
