### ISSUE TITLE
Align Navbar Items

### ISSUE THREAD

**Issue by Prashant0664** [Prashant0664/Blog-website#19]
Items in navbar are not aligned properly
<img width="1440" alt="Screenshot 2024-10-07 at 9 06 10 PM" src="https://github.com/user-attachments/assets/7ee985c8-d1c9-44b3-881d-e65a5f002aeb">

as you can see in the image. 
Align all items properly to the central line.
Note: You do not need to setup backend for this. Just clone and run the frontend.

Don't forgot to stand the repo or follow github.

**Comment by Jai-Marothiya** [comment]
Hello @Prashant0664 - Please assign this issue to me.

**Comment by Prashant0664** [comment]
Assigned @Jai-Marothiya

**Comment by Jai-Marothiya** [comment]
Hello @Prashant0664 - I raised its PR. Please take a look.
