### ISSUE TITLE
Any Improvement in UI/UX/Frontend is welcomed

### ISSUE THREAD

**Issue by Prashant0664** [Prashant0664/Blog-website#20]
Improve any feature or look in frontend.
Just clone, change and create pull request. So simple.
For frontend, you may not need to use backend depending on the part you want to change/improve.
Note: Final acceptance depends on us. 

Don't forgot to star the repo or follow my github for amazing projects😊

**Comment by Jai-Marothiya** [comment]
Hello @Prashant0664 - I think there is an issue in Header, like you found "Add" is not properly aligning and also the text below header should be in same with as header content and I thing It would be better if there is an footer in page. Could you please assign this issue to me? So that I can move forward to fix these issues.

**Comment by Prashant0664** [comment]
This is open to everyone. Just raise PR and I will merge and close it with relevant tags.
@Jai-Marothiya You can work on footer and navbar.

**Comment by irekponor** [comment]
@Prashant0664 As a UI/UX designer, I feel the interface could benefit from some refinement. i should be able to improve it well kindly assign it to me so i can try improving it

**Comment by Prashant0664** [comment]
@irekponor this issue is open to everyone. Just suggest and make changes and raise PR, I will review and merge PR with relevant tags accordingly.

**Comment by Jai-Marothiya** [comment]
@Prashant0664 - I raised one PR please take a look into it.

**Comment by huzaifsk** [comment]
Please review my PR @Prashant0664 I have added some improvements. Thank you

**Comment by Prashant0664** [comment]
@huzaifsk PR merged

**Comment by Prashant0664** [comment]
@Jai-Marothiya navbar not fixed for all screens, it is going out of screen for certain dimensions. Please fix this
<img width="827" alt="image" src="https://github.com/user-attachments/assets/72f0fca8-b44c-4d9e-9fe8-4132061ef7f8">

**Comment by Jai-Marothiya** [comment]
@Prashant0664 - I'll fix it soon in different PR.

**Comment by MichalT106** [comment]
Hi, is there any work what I can do? Some UI,UX or responsivness needed? I would like to do it and make PR.

**Comment by Prashant0664** [comment]
> Hi, is there any work what I can do? Some UI,UX or responsivness needed? I would like to do it and make PR.

You can suggest and improve any features on the frontend side. Just get your idea approved before making changes.
