### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by Prashant0664** [Prashant0664/Blog-website#28]
Add a simple footer which contains various links (not needed to direct to certain pages for now)

**Comment by TusharGupta-Developer** [comment]
I believe there is already a footer in place based on what I saw in the repository. Do you want to add anything to it?

**Comment by Prashant0664** [comment]
@TusharGupta-Developer Footer on home page.

**Comment by TusharGupta-Developer** [comment]
I hope you're doing well. I wanted to follow up on the pull request I submitted a few days ago regarding Add footer #28. I understand you may be busy, but I would really appreciate your feedback whenever you get a chance to review it.

**Comment by Prashant0664** [comment]
> I hope you're doing well. I wanted to follow up on the pull request I submitted a few days ago regarding Add footer #28. I understand you may be busy, but I would really appreciate your feedback whenever you get a chance to review it.

PR merged
