### ISSUE TITLE
Fix profile image size

### ISSUE THREAD

**Issue by Prashant0664** [Prashant0664/Blog-website#29]
Fix image size of profile in article section so that it is perfect circle for all screen sizes without affecting other elements/components. You do not need to setup backend for this task.
<img width="539" alt="image" src="https://github.com/user-attachments/assets/8633ccab-9443-408c-a06a-2cb790a2ce61">

**Comment by Sachita007** [comment]
Could you assign this to me? I would like to work on it.

**Comment by Prashant0664** [comment]
@Sachita007 assigned
