### ISSUE TITLE
Make Navbar Responsive

### ISSUE THREAD

**Issue by Prashant0664** [Prashant0664/Blog-website#32]
Navbar is not responsive for all screen sizes. Its components get out of screen for certain dimensions of screen (width: 826px-965px, <=585px ). Make sure to fix navbar both before sign in and after sign in;
Note: You may not need to setup backend for this

**Comment by AdityaJ2305** [comment]
Hey @Prashant0664 , I would like to work on this issue. Could you assign it to me ?

**Comment by Prashant0664** [comment]
@AdityaJ2305 assigned

**Comment by Prashant0664** [comment]
@AdityaJ2305 any update?

**Comment by AdityaJ2305** [comment]
@Prashant0664  Will be done by EOD ?

**Comment by AdityaJ2305** [comment]
@Prashant0664, I need to unassign myself from this issue. Apologies and thank you for understanding .
