### ISSUE TITLE
Add a Dark mode

### ISSUE THREAD

**Issue by Lakshita-Kumawat** [Prashant0664/Blog-website#35]
@Prashant0664  Your website is lacking a dark mode. I can give it a try assign me

**Comment by Prashant0664** [comment]
@Lakshita-Kumawat assigned

**Comment by Lakshita-Kumawat** [comment]
Ok i will start working. Pls also label hacktoberfest. It will be my very first contribution

**Comment by Lakshita-Kumawat** [comment]
@Prashant0664 when i try to use npm start in backend it says OAuth2Strategy requires a clientId option. What should i do?

**Comment by Prashant0664** [comment]
you have to setup .env file. https://github.com/Prashant0664/Blog-website/blob/master/backend/README.md you only need to set it up for local development not for production.
OAuth2Strategy is used to sign-in using google which can easily be generated by going to google console. (refer any TY video for this.)

**Comment by Lakshita-Kumawat** [comment]
Ok
