### ISSUE TITLE
Add a dark theme option to the website home page

### ISSUE THREAD

**Issue by Prashant0664** [Prashant0664/Blog-website#7]
Add a working dark theme option/button to the website for homepage. Website should remain in the dark theme on refreshing the page. For any query you can leave an comment.

**Comment by shivanshsin0203** [comment]
I wish to solve this issue please assign me to it.

**Comment by Prashant0664** [comment]
Assigned to @shivanshsin0203

**Comment by chandra1899** [comment]
Could u provide me any figma sample for reference of colors to be used in dark mode
