### ISSUE TITLE
Decrease border radius of Search bar to 10px

### ISSUE THREAD

**Issue by Prashant0664** [Prashant0664/Blog-website#8]

**Comment by joshijoe05** [comment]
Hello, I would like to work on this issue, Assign this to me
If possible add some screenshots where to modify

**Comment by Prashant0664** [comment]
<img width="1203" alt="Screenshot 2023-10-02 at 3 27 32 PM" src="https://github.com/Prashant0664/Blog-website/assets/98750053/87aad4e3-f0a1-4b32-9b23-b27de4f399fe">
Assigned to @joshijoe05 
You have to modify search bar so that its border radius looks similar to that of posts.
Check in Navbar.js file in frontend for code.

**Comment by DHRUVKHANDELWAL00** [comment]
hey @Prashant0664 , can i work on this?...it wont take time

**Comment by Prashant0664** [comment]
Yes, you can work on this @DHRUVKHANDELWAL00
