### ISSUE TITLE
Decrease gap between Post heading and post description

### ISSUE THREAD

**Issue by Prashant0664** [Prashant0664/Blog-website#9]
Decrease the gap between Post heading and its brief description on home page.

**Comment by joshijoe05** [comment]
Hello, I would like to work on this issue, Please assign this to me and if possible elaborate the issue

**Comment by Prashant0664** [comment]
Assigned to @joshijoe05 
<img width="1290" alt="Screenshot 2023-10-02 at 3 35 38 PM" src="https://github.com/Prashant0664/Blog-website/assets/98750053/1fb25526-e31d-46ef-96f8-63125e1700a8">
Reduce gap marked as red between heading and description.

**Comment by joshijoe05** [comment]
Can you assign the issue to me,
I have a little doubt, should i need to create a .env file?

**Comment by Prashant0664** [comment]
Yes, you have to create .env for backend, its format is given in backend README.md

**Comment by mahesh3536** [comment]
Is this issue solved or not solved ?

**Comment by mahesh3536** [comment]
If not solved please assign me to this task
